ArticlesApp/ArticlesApp/Models/ArticleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ArticlesApp.Models
{
    public class ArticleModel
    {
        
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Categorie { get; set; }
        public string Manufacturer { get; set; }
        public string Supplier { get; set; }
        public decimal Price { get; set; }
    }
    
    

}

ArticlesApp/ArticlesApp/Controllers/ReadWriteController.cs
using ArticlesApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace ArticlesApp.Controllers
{
    public class ReadWriteController : Controller
    {
        // GET: ReadWrite
        public ActionResult Index()
        {
            return View();
        }

        // GET: ReadWrite/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ReadWrite/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ReadWrite/Create
        [HttpPost]
        public ActionResult Create(ArticleModel articleModel)
        {
            try
            {
                List<ArticleModel> item = new List<ArticleModel>();
                ReadWriteJson readInsert = new ReadWriteJson();

                string mainPath = AppDomain.CurrentDomain.BaseDirectory;
                string path = mainPath + @"\App_Data\source.json";
                item = JsonConvert.DeserializeObject<List<ArticleModel>>(readInsert.Read(path));

                if (item.Count == 0)
                {
                    articleModel.Id = 1;
                    item.Add(articleModel);
                }
                else
                {
                    int maxId = item.Max(x => x.Id);
                    int nextIndex = maxId + 1;
                    articleModel.Id = nextIndex;
                    item.Add(articleModel);
                }           

                string result = JsonConvert.SerializeObject(item);
                readInsert.Insert(path, result);

                return RedirectToAction("Index", "ShowItems");                
            }
            catch
            {
                return View();
            }
        }

        // GET: ReadWrite/Edit/5
        public ActionResult Edit(int id)
        {
            List<ArticleModel> item = new List<ArticleModel>();
            ReadWriteJson check = new ReadWriteJson();

            string mainPath = AppDomain.CurrentDomain.BaseDirectory;
            string path = mainPath + @"\App_Data\source.json";
            item = JsonConvert.DeserializeObject<List<ArticleModel>>(check.Read(path));

            ArticleModel article = item.FirstOrDefault(x => x.Id == id);
            return View(article);
        }

        // POST: ReadWrite/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, ArticleModel articleModel)
        {
            try
            {
                List<ArticleModel> item = new List<ArticleModel>();
                ReadWriteJson edit = new ReadWriteJson();

                string mainPath = AppDomain.CurrentDomain.BaseDirectory;
                string path = mainPath + @"\App_Data\source.json";
                item = JsonConvert.DeserializeObject<List<ArticleModel>>(edit.Read(path));

                ArticleModel article = item.FirstOrDefault(x => x.Id == articleModel.Id);

                int index = item.FindIndex(x => x.Id == id);
                item[index] = articleModel;

                string jSONString = JsonConvert.SerializeObject(item);
                edit.Insert(path, jSONString);

                return RedirectToAction("Index", "ShowItems");
            }
            catch
            {
                return View();
            }
        }

        // GET: ReadWrite/Delete/5
        public ActionResult Delete(int? id)
        {
            List<ArticleModel> item = new List<ArticleModel>();
            ReadWriteJson check = new ReadWriteJson();

            string mainPath = AppDomain.CurrentDomain.BaseDirectory;
            string path = mainPath + @"\App_Data\source.json";
            item = JsonConvert.DeserializeObject<List<ArticleModel>>(check.Read(path));

            ArticleModel article = item.FirstOrDefault(x => x.Id == id);
            
            return View(article);
        }

        // POST: ReadWrite/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                List<ArticleModel> item = new List<ArticleModel>();
                ReadWriteJson check = new ReadWriteJson();

                string mainPath = AppDomain.CurrentDomain.BaseDirectory;
                string path = mainPath + @"\App_Data\source.json";
                item = JsonConvert.DeserializeObject<List<ArticleModel>>(check.Read(path));
                
                int index = item.FindIndex(x => x.Id == id);
                
                item.RemoveAt(index);
                string jSONString = JsonConvert.SerializeObject(item);
                check.Insert(path, jSONString);

                return RedirectToAction("Index", "ShowItems");
            }
            catch
            {
                return View();
            }
        }
    }
    public class ReadWriteJson
    {
        public ReadWriteJson() { }

        public string Read(string path)
        {
            string result;
            using (StreamReader strRead = new StreamReader(path))
            {
                result = strRead.ReadToEnd();
            }
            return result;
        }
        public void Insert(string path, string jSonString)
        {
            using (var strInsert = File.CreateText(path))
            {
                strInsert.Write(jSonString);
            }
        }

    }
}

ArticlesApp/ArticlesApp/Controllers/ShowItemsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using ArticlesApp.Models;
using Newtonsoft.Json;

namespace ArticlesApp.Controllers
{
    public class ShowItemsController : Controller
    {
        // GET: ShowItems
        public ActionResult Index()
        {
            List<ArticleModel> item = new List<ArticleModel>();
            ReadWriteJson view = new ReadWriteJson();

            string mainPath = AppDomain.CurrentDomain.BaseDirectory;
            string path = mainPath + @"\App_Data\source.json";

            item = JsonConvert.DeserializeObject<List<ArticleModel>>(view.Read(path));
            
            return View(item);          
        }       
    }   
}

ArticlesApp/ArticlesApp/Views/ReadWrite/Create.cshtml
@model ArticlesApp.Models.ArticleModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ArticleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supplier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "ShowItems")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArticlesApp/ArticlesApp/Views/ReadWrite/Delete.cshtml
@model ArticlesApp.Models.ArticleModel

@{
    ViewBag.Title = "Delete Item";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ArticleModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index","ShowItems")
        </div>
    }
</div>

ArticlesApp/ArticlesApp/Views/ReadWrite/Edit.cshtml
@model ArticlesApp.Models.ArticleModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ArticleModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supplier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "ShowItems")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArticlesApp/ArticlesApp/Views/Remove/index.cshtml
@model ArticlesApp.Models.ArticleModel

@{
    ViewBag.Title = "Remove";
}

<h2>Remove</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ArticleModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "Remove")
        </div>
    }
</div>

ArticlesApp/ArticlesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Article ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ArticlesApp/ArticlesApp/Views/ShowItems/Index.cshtml
@model IEnumerable<ArticlesApp.Models.ArticleModel>

@{
    ViewBag.Title = "Show Items";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "ReadWrite")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categorie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supplier)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id).
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categorie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Manufacturer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price) &euro;
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "ReadWrite", new { id = item.Id }, null)|           
            @Html.ActionLink("Delete", "Delete", "ReadWrite", new { id = item.Id }, null)
        </td>
    </tr>
}

</table>